### ISSUE TITLE
[Feature Reqest] Export deadlines with iCal

### ISSUE THREAD

**Issue by richard-hajek** [ReCodEx/api#415]
## Issue Description

I would love to be able to automatically export tasks from ReCodEx and add them into my Google Calendar (as I don't actually visit ReCodEx that often, especially in the last few weeks of semester)

## HTTP Request Example

`https://recodex.mff.cuni.cz/api/v1/export_ical?token=<token of user of subject>`

## Expected Behaviour

API would return tasks as iCalendar formatted events

## Actual Results

Such API doesn't exist

**Comment by krulis-martin** [comment]
Such feature request was already registered in web-app. Although it is a good feature, I cannot give you any estimates regarding when it will be prioritized.

**Comment by richard-hajek** [comment]
I see, closing as duplicate then
